# Generated by Django 5.1.6 on 2025-02-08 20:42

from django.db import migrations, models
from src.preferences.models import Preference
from src.preferences.schemas import DTYPE


def create_default_preferences(apps, schema_editor):
    Preference.objects.bulk_create(
        [
            Preference(
                key="LANG",
                dtype=DTYPE.STRING,
                description="Default language for the application",
            ),
            Preference(
                key="default_timezone",
                dtype=DTYPE.STRING,
                description="Default timezone for the application",
            ),
            Preference(
                key="default_date_format",
                dtype=DTYPE.STRING,
                description="Default date format for the application",
            ),
            Preference(
                key="default_time_format",
                dtype=DTYPE.STRING,
                description="Default time format for the application",
            ),
        ]
    )


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Preference",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "key",
                    models.CharField(max_length=30, primary_key=True, serialize=False),
                ),
                (
                    "dtype",
                    models.IntegerField(
                        choices=[
                            (0, "STRING"),
                            (1, "INT"),
                            (2, "FLOAT"),
                            (3, "BOOL"),
                            (4, "JSON"),
                        ],
                        default=0,
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.RunPython(create_default_preferences),
    ]
