# Generated by Django 5.1.6 on 2025-02-09 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_manager", "0003_user_dp_alter_user_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="cover",
            field=models.ImageField(
                default="../static/default-cover.jpg", upload_to="cover_pics"
            ),
        ),
    ]
