# Generated by Django 5.1.6 on 2025-02-10 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("preferences", "0002_auto_20250209_0224"),
        ("user_manager", "0004_user_cover"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="userpreference",
            unique_together={("user", "preference")},
        ),
    ]
